controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
prestataire_test:
    path: /prestataire/test
    controller: App\Controller\PrestataireController
